name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: test
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Push to gh-pages branch
        run: |
          pwd
          ls
          git fetch
          git checkout gh-pages
          mkdir -p gh-pages-dir
          # cd gh-pages-dir
          touch index.html
          cat << EOF > index.html
          <!DOCTYPE html>
          <html> 
          <body>
          <h1>My Latest changes served from root dir</h1>
          <p>My latest paragraph.</p>
          </body>
          </html>
          EOF
          # cd gh-pages
          # git fetch
          
          # git config --local user.email "github-actions[bot]@users.noreply.github.com"
          # git config --local user.name "github-actions[bot]"
          # git add .
          # git commit -a -m "Add changes" || true
      
      # - name: Push changes
      #   if: ${{ always() }}
      #   uses: ad-m/github-push-action@master
      #   with:
      #     branch: gh-pages
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-dir
          publish_branch: gh-pages
